# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[directory]
truncation_length = 100
truncation_symbol = "…/"
truncate_to_repo = false
style = "#FFD700"

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
format="$symbol "
success_symbol = "[❯](bold #32cd32)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red) "
vimcmd_symbol = "[N](bold #32cd32)"
vimcmd_visual_symbol = "[V](bold #32cd32)"

[aws]
format = "[aws:$profile]($style) "
style = "#ff8c00"

[python]
style = "bold #ff8c00"
format = '[${symbol}${pyenv_prefix}(${version} )]($style)'

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold #ff8c00"

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[time]
format = "[$time]($style) "
style = "#32cd32"
disabled = false

[cmd_duration]
show_milliseconds = true
format = ' [󱫌 $duration]($style)'
